# Generated by Django 5.2.7 on 2025-10-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_pricehistory_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
