# Generated by Django 5.2.7 on 2025-11-25 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_alter_pricehistory_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptocurrency",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cryptocurrency",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cryptocurrency",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
